# Generated by Django 5.0.3 on 2024-03-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comment_commenter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter_email',
        ),
    ]
