# Generated by Django 5.0.3 on 2024-03-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.status'),
        ),
    ]
