# Generated by Django 5.0.3 on 2024-03-30 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='home.status'),
        ),
    ]
